### ISSUE TITLE
Tags are not pushed to Dockerhub

### ISSUE THREAD

**Issue by ktk** [zazukoians/docker-node-java-jena#3]
It looks like the tags do not make it to [Dockerhub](https://hub.docker.com/r/zazukoians/node-java-jena/tags?page=1&ordering=last_updated) and I don't understand why.

Could you check that out @ludovicm67?

**Comment by ludovicm67** [comment]
We decided to have a standard way to tag a semver version on all projects; you should have the `v` prefix in tags.

For example `3.17.0` should be `v3.17.0`. This should work. Can you try it?

**Comment by ktk** [comment]
ok that worked but then the idea is that I have to provide `v3...` in referencing the image and not just `3...`?

**Comment by ludovicm67** [comment]
Yes!

The GitHub Action is configured to create the following tags:

- `pipeline-PID` where `PID` is the ID of pipeline run
- `git-SHA` where `SHA` is the current git commit sha
- `vX`, `vX.Y` and `vX.Y.Z` where `X.Y.Z` is a semver-compatible version, when a version is tagged (using a `vX.Y.Z` tag)
- `branch-NAME` where `NAME` is the name of the branch where the commit was pushed
- `git-NAME-SHA` where `NAME` is the name of the branch where the commit was pushed and `SHA` is the current git commit sha
- `latest` if this commit was done on the default branch

**Comment by ludovicm67** [comment]
@ktk can this issue be closed?
